### ISSUE TITLE
not accepting --token flag

### ISSUE THREAD

**Issue by rrshaban** [peterdemin/openai-cli#4]
I'm noting that the CLI requires the interface to be "openai repl -t KEY"
in the examples below, I tried "openai -t key repl" and it would fail uninformatively

```
% openai repl  
Usage: openai repl [OPTIONS]
Try 'openai repl --help' for help.

Error: Either --token option or OPENAI_API_TOKEN environment variable must be provided
```

```
% openai --token '<...>' repl
Usage: openai [OPTIONS] COMMAND [ARGS]...
Try 'openai --help' for help.

Error: No such option: --token
```

% openai -t '...' repl
Usage: openai [OPTIONS] COMMAND [ARGS]...
Try 'openai --help' for help.

Error: No such option: -t

**Comment by peterdemin** [comment]
The order is different: `openai repl --token "<...>"`
