### ISSUE TITLE
Support non-OpenAI.com instances feature request

### ISSUE THREAD

**Issue by UnoSD** [peterdemin/openai-cli#5]
I would like to suggest supporting also other instances (E.G. Azure OpenAI). It may be just as simple as an envvar that can set the base URL.

Thank you.

**Comment by peterdemin** [comment]
I don't have access to other APIs, but I would be happy to review a PR. URL override through env var is fine.

**Comment by UnoSD** [comment]
I will give it a go, although Python is not really my element

**Comment by peterdemin** [comment]
Resolved in #6

**Comment by peterdemin** [comment]
Thanks! The changes are in the [0.0.3](https://pypi.org/project/openai-cli/0.0.3/) release!
